### ISSUE TITLE
Predicting next 60 days using pytorch (LSTM)

### ISSUE THREAD

**Issue by Akaori** [jkotra/TimeSeries#1]
Hello @jkotra,

I was checking your pytorch work with time-series. I would like to know how can we use the model to predict the next 60 days for example ?

I saw you did this for the next day :

```
#array --> List
today = total_x[-1].reshape(-1).tolist()

# scaling last price
last_price = scaler.transform(infered['y_pred'][-1].reshape(-1, 1))

# adding last price to list.
today.append(last_price[0])

# Exclude first(0th index) element
today = today[1:]

#reshape
today = np.array(today).reshape(-1,60,1)

today = torch.Tensor(list(today))

#predict!
tomorrow = predict_with_pytorch(model, today)

#inverse transform.
tomorrow = scaler.inverse_transform(tomorrow)[0]
```

How to predict the next 60 days ?

**Comment by jkotra** [comment]
check [updated notebook](https://github.com/jkotra/TimeSeries/blob/master/StockPricePrediction/Predicting_StockPrice_Pytorch1.0%2B.ipynb) 👍
